server:
  port: 20000
  servlet:
    session:
      timeout: 30m

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #配置nacos地址

  #开发环境关闭缓存
  thymeleaf:
    cache: false
  redis:
    host: 192.168.150.132
    port: 6379

  session:
    store-type: redis